/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stacja;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Katarzyna
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
    public AdminPanel() {
        initComponents();

        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);

            }

        });
        
        idCompLabel.setVisible(false);
        jLabel12.setVisible(false);
        hasloLabel.setVisible(false);
        hasloField.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changingPanel2 = new javax.swing.JPanel();
        klienciCard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        newClientPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        newNameField = new javax.swing.JTextField();
        newSurnameField = new javax.swing.JTextField();
        newCompanyField = new javax.swing.JTextField();
        newMailField = new javax.swing.JTextField();
        newPhoneField = new javax.swing.JTextField();
        newAddressField = new javax.swing.JTextField();
        newCodeField = new javax.swing.JTextField();
        newCityField = new javax.swing.JTextField();
        newNIPField = new javax.swing.JTextField();
        newRegonField = new javax.swing.JTextField();
        newUserBtn = new javax.swing.JButton();
        editUserBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idCompLabel = new javax.swing.JLabel();
        hasloLabel = new javax.swing.JLabel();
        hasloField = new javax.swing.JPasswordField();
        companyPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CompanyTable = new javax.swing.JTable();
        editCompanyBtn = new javax.swing.JButton();
        deleteCompanyBtn = new javax.swing.JButton();
        programPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tank95Field = new javax.swing.JTextField();
        tank98Field = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tankONField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tankowanieelpegie = new javax.swing.JLabel();
        tankLPGField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        mycieField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        woskField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        changePointsBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        benzPointsField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lpgPointsField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        washField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        waxField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        changePoints2Btn = new javax.swing.JButton();
        PricePanel = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        washTextField = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        ONTextField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        oil1TextField = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        gasTextField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        oil2TextField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        wash2TextField = new javax.swing.JTextField();
        SaveChangesBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        newMenu = new javax.swing.JMenu();
        klientsItem = new javax.swing.JMenuItem();
        companyItem = new javax.swing.JMenuItem();
        newKlientItem = new javax.swing.JMenuItem();
        loyProgMenu = new javax.swing.JMenu();
        rulesItem = new javax.swing.JMenuItem();
        washMenu = new javax.swing.JMenu();
        washItem = new javax.swing.JMenuItem();
        cameraMenu = new javax.swing.JMenu();
        cameraItem = new javax.swing.JMenuItem();
        priceMenu = new javax.swing.JMenu();
        changePriceMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logoffItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changingPanel2.setLayout(new java.awt.CardLayout());

        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Klienta", "Imię", "Nazwisko", "e-mail", "Nr telefonu", "Ulica", "Kod pocztowy", "Miasto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(clientsTable);
        if (clientsTable.getColumnModel().getColumnCount() > 0) {
            clientsTable.getColumnModel().getColumn(0).setResizable(false);
            clientsTable.getColumnModel().getColumn(0).setPreferredWidth(3);
            clientsTable.getColumnModel().getColumn(1).setResizable(false);
            clientsTable.getColumnModel().getColumn(2).setResizable(false);
            clientsTable.getColumnModel().getColumn(3).setResizable(false);
            clientsTable.getColumnModel().getColumn(4).setResizable(false);
            clientsTable.getColumnModel().getColumn(5).setResizable(false);
            clientsTable.getColumnModel().getColumn(6).setResizable(false);
            clientsTable.getColumnModel().getColumn(7).setResizable(false);
        }

        editBtn.setText("Edytuj");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Usuń");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klienciCardLayout = new javax.swing.GroupLayout(klienciCard);
        klienciCard.setLayout(klienciCardLayout);
        klienciCardLayout.setHorizontalGroup(
            klienciCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klienciCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(klienciCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(klienciCardLayout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)))
        );
        klienciCardLayout.setVerticalGroup(
            klienciCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klienciCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(klienciCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        changingPanel2.add(klienciCard, "klienciCard");

        jLabel1.setText("Imie");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Nazwa firmy");

        jLabel4.setText("Adres e-mail");

        jLabel5.setText("Numer telefonu");

        jLabel6.setText("Ulica i numer domu");

        jLabel7.setText("Kod pocztowy");

        jLabel8.setText("Miasto");

        jLabel9.setText("NIP");

        jLabel10.setText("Regon");

        newUserBtn.setText("Dodaj");
        newUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserBtnActionPerformed(evt);
            }
        });

        editUserBtn.setText("Edytuj");
        editUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Numer ID klienta");

        jLabel12.setText("Numer ID firmy");

        hasloLabel.setText("Hasło");

        javax.swing.GroupLayout newClientPanelLayout = new javax.swing.GroupLayout(newClientPanel);
        newClientPanel.setLayout(newClientPanelLayout);
        newClientPanelLayout.setHorizontalGroup(
            newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newClientPanelLayout.createSequentialGroup()
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newNameField)
                            .addComponent(newSurnameField)
                            .addComponent(newCompanyField)
                            .addComponent(newMailField)
                            .addComponent(newPhoneField)
                            .addComponent(newAddressField)
                            .addComponent(newCodeField)
                            .addComponent(newCityField)
                            .addComponent(newNIPField)
                            .addComponent(newRegonField, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClientPanelLayout.createSequentialGroup()
                        .addComponent(newUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(editUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(hasloLabel))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(idCompLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hasloField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        newClientPanelLayout.setVerticalGroup(
            newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newClientPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newClientPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(newSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newClientPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(idCompLabel))))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newCompanyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasloLabel)
                    .addComponent(hasloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newMailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newNIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(newRegonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(newClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(editUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        changingPanel2.add(newClientPanel, "newClientPanel");

        CompanyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Firmy", "Nazwa", "NIP", "Regon", "Właściciel", "ID właściciela"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CompanyTable);
        if (CompanyTable.getColumnModel().getColumnCount() > 0) {
            CompanyTable.getColumnModel().getColumn(0).setResizable(false);
            CompanyTable.getColumnModel().getColumn(0).setPreferredWidth(3);
            CompanyTable.getColumnModel().getColumn(1).setResizable(false);
            CompanyTable.getColumnModel().getColumn(2).setResizable(false);
            CompanyTable.getColumnModel().getColumn(3).setResizable(false);
            CompanyTable.getColumnModel().getColumn(4).setResizable(false);
            CompanyTable.getColumnModel().getColumn(5).setResizable(false);
            CompanyTable.getColumnModel().getColumn(5).setPreferredWidth(2);
        }

        editCompanyBtn.setText("Edytuj");
        editCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCompanyBtnActionPerformed(evt);
            }
        });

        deleteCompanyBtn.setText("Usuń");
        deleteCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompanyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout companyPanelLayout = new javax.swing.GroupLayout(companyPanel);
        companyPanel.setLayout(companyPanelLayout);
        companyPanelLayout.setHorizontalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyPanelLayout.createSequentialGroup()
                        .addComponent(editCompanyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(deleteCompanyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        companyPanelLayout.setVerticalGroup(
            companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(companyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(editCompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        changingPanel2.add(companyPanel, "companyPanel");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Poniżej podano ilość punktów, którą klienci otrzymują za tankowanie bądź mycie w ramach programu lojalnościowego stacji.");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tankowanie");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("95");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("98");

        tank95Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tank95FieldActionPerformed(evt);
            }
        });

        jLabel17.setText("pkt/l");

        jLabel18.setText("pkt/l");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("ON");

        jLabel20.setText("pkt/l");

        tankowanieelpegie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tankowanieelpegie.setForeground(new java.awt.Color(255, 0, 0));
        tankowanieelpegie.setText("LPG");

        jLabel21.setText("pkt/l");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Mycie");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Mycie standardowe");

        jLabel24.setText("pkt");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Mycie z woskowaniem");

        jLabel26.setText("pkt");

        changePointsBtn.setText("Zmień");
        changePointsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePointsBtnActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Poniżej podano ilość punktów, które klienci muszą uzyskać, aby móc skorzystać z darmowych usług w ramach programu lojalnościowego.");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("benzyna/ON");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("LPG");

        jLabel30.setText("pkt/l");

        jLabel31.setText("pkt/l");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("Mycie standardowe");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("Mycie z woskowaniem");

        jLabel34.setText("pkt");

        jLabel35.setText("pkt");

        changePoints2Btn.setText("Zmień");
        changePoints2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePoints2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programPanelLayout = new javax.swing.GroupLayout(programPanel);
        programPanel.setLayout(programPanelLayout);
        programPanelLayout.setHorizontalGroup(
            programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(programPanelLayout.createSequentialGroup()
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(programPanelLayout.createSequentialGroup()
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19)
                                    .addComponent(tankowanieelpegie))
                                .addGap(22, 22, 22)
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tank95Field)
                                    .addComponent(tank98Field)
                                    .addComponent(tankONField)
                                    .addComponent(tankLPGField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))))
                        .addGap(286, 286, 286)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(programPanelLayout.createSequentialGroup()
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(mycieField)
                                    .addComponent(woskField, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26)))
                            .addComponent(changePointsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel27)
                    .addGroup(programPanelLayout.createSequentialGroup()
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(37, 37, 37)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(benzPointsField)
                            .addComponent(lpgPointsField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(223, 223, 223)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(programPanelLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(waxField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                            .addGroup(programPanelLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(25, 25, 25)
                                .addComponent(washField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34))
                            .addComponent(changePoints2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        programPanelLayout.setVerticalGroup(
            programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tank95Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23)
                    .addComponent(mycieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(32, 32, 32)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tank98Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel25)
                    .addComponent(woskField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(28, 28, 28)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tankONField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tankowanieelpegie)
                            .addComponent(tankLPGField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(programPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(changePointsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(benzPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(washField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(25, 25, 25)
                .addGroup(programPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lpgPointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(waxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(28, 28, 28)
                .addComponent(changePoints2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        changingPanel2.add(programPanel, "programPanel");

        jLabel36.setText("Podaj nową cenę usług:");

        jLabel37.setText("ON");

        jLabel38.setText("95");

        jLabel39.setText("98");

        jLabel40.setText("LPG");

        jLabel41.setText("Mycie");

        jLabel42.setText("Mycie z woskowaniem");

        SaveChangesBtn.setText("Zapisz");
        SaveChangesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveChangesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PricePanelLayout = new javax.swing.GroupLayout(PricePanel);
        PricePanel.setLayout(PricePanelLayout);
        PricePanelLayout.setHorizontalGroup(
            PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricePanelLayout.createSequentialGroup()
                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PricePanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PricePanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PricePanelLayout.createSequentialGroup()
                                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PricePanelLayout.createSequentialGroup()
                                        .addGap(355, 355, 355)
                                        .addComponent(jLabel39))))
                            .addGroup(PricePanelLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(54, 54, 54)
                                .addComponent(washTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(jLabel42)))
                        .addGap(18, 18, 18)
                        .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wash2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PricePanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(SaveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(440, Short.MAX_VALUE))
            .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricePanelLayout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(ONTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(823, Short.MAX_VALUE)))
            .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricePanelLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(oil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(825, Short.MAX_VALUE)))
        );
        PricePanelLayout.setVerticalGroup(
            PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PricePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel36)
                .addGap(28, 28, 28)
                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PricePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PricePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addGap(43, 43, 43)))
                .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(washTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(wash2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(SaveChangesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricePanelLayout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(ONTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
            .addGroup(PricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PricePanelLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(oil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );

        changingPanel2.add(PricePanel, "priceCard");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ls7OxP.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel43.setText("KAMERA FRONT");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kam2.gif"))); // NOI18N
        jButton2.setText("jButton2");

        jLabel44.setText("KAMERA STANOWISKA");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kam3.gif"))); // NOI18N
        jButton3.setText("jButton3");

        jLabel45.setText("KAMERA WYJAZD");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kam4.gif"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel44)
                        .addGap(759, 759, 759))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel43)
                                .addGap(250, 250, 250)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(212, 212, 212))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel45))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        changingPanel2.add(jPanel1, "cardMoni");

        newMenu.setText("Klienci");
        newMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMenuMouseClicked(evt);
            }
        });
        newMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuActionPerformed(evt);
            }
        });

        klientsItem.setText("Zarejestrowani klienci");
        klientsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientsItemActionPerformed(evt);
            }
        });
        newMenu.add(klientsItem);

        companyItem.setText("Firmy");
        companyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyItemActionPerformed(evt);
            }
        });
        newMenu.add(companyItem);

        newKlientItem.setText("Dodaj klienta");
        newKlientItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newKlientItemActionPerformed(evt);
            }
        });
        newMenu.add(newKlientItem);

        jMenuBar1.add(newMenu);

        loyProgMenu.setText("Program lojalnościowy");

        rulesItem.setText("Zasady programu");
        rulesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesItemActionPerformed(evt);
            }
        });
        loyProgMenu.add(rulesItem);

        jMenuBar1.add(loyProgMenu);

        washMenu.setText("Myjnia");

        washItem.setText("Kalendarz");
        washItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washItemActionPerformed(evt);
            }
        });
        washMenu.add(washItem);

        jMenuBar1.add(washMenu);

        cameraMenu.setText("Monitoring");

        cameraItem.setText("Kamery");
        cameraItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraItemActionPerformed(evt);
            }
        });
        cameraMenu.add(cameraItem);

        jMenuBar1.add(cameraMenu);

        priceMenu.setText("Ceny");

        changePriceMenu.setText("Ustal ceny");
        changePriceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePriceMenuActionPerformed(evt);
            }
        });
        priceMenu.add(changePriceMenu);

        jMenuBar1.add(priceMenu);

        jMenu1.setText("Wyloguj");

        logoffItem.setText("Wyloguj z panelu administracyjnego");
        logoffItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoffItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(changingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void klientsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klientsItemActionPerformed
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "klienciCard");
        
        FillTable uzupelnij = new FillTable();

        uzupelnij.ClearTable(clientsTable);
        
        String wybierzKlientow = "select kli_id, kli_imie, kli_nazwisko, kli_mail, kli_telefon, adr_ulica, adr_kod, "
                + "adr_miasto from klient, adres where kli_id=adr_klient_id and adr_id=kli_adres_id";

        try {
            Connection conn = DataBase.Connection();
            pst = conn.prepareStatement(wybierzKlientow);
            rs = pst.executeQuery();
            
            uzupelnij.FillClients(clientsTable, rs);
            pst.close(); rs.close();
            
            conn.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w AdminPanel: " + ex);
        }
        
    }//GEN-LAST:event_klientsItemActionPerformed

    private void newMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMenuMouseClicked
        
    }//GEN-LAST:event_newMenuMouseClicked

    private void newMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuActionPerformed

    }//GEN-LAST:event_newMenuActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        
        int index = clientsTable.getSelectedRow();
        System.out.println("Wybrany index" + index);
        String nr_id = (String) clientsTable.getValueAt(index, 0);
        String imie = (String) clientsTable.getValueAt(index, 1);
        String nazwisko = (String) clientsTable.getValueAt(index, 2);
        String mail = (String) clientsTable.getValueAt(index, 3);
        String telefon = (String) clientsTable.getValueAt(index, 4);
        String ulica = (String) clientsTable.getValueAt(index, 5);
        String kod = (String) clientsTable.getValueAt(index, 6);
        String miasto = (String) clientsTable.getValueAt(index, 7);
        
        String firma = "", nip = "", regon = "";
        
        String wybierzFirme = "select * from Firma where fir_klient_id=" + nr_id;
        
        try {
            Connection conn = DataBase.Connection();
            
            pst = conn.prepareStatement(wybierzFirme);
            rs = pst.executeQuery();
            
            if(rs.next()) {
                firma = rs.getString("fir_nazwa");
                nip = rs.getString("fir_nip");
                regon = rs.getString("fir_regon");
            }
            
            pst.close(); rs.close(); conn.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w wyszukaniu firmy dla podanego klienta " + ex);
        }
        
        if(evt.getSource()== editBtn) {
            CardLayout card = (CardLayout) changingPanel2.getLayout();
            card.show(changingPanel2, "newClientPanel");
            
            newUserBtn.setVisible(false);
            
            idLabel.setText(nr_id);
            newNameField.setText(imie);
            newSurnameField.setText(nazwisko);
            newMailField.setText(mail);
            newPhoneField.setText(telefon);
            newAddressField.setText(ulica);
            newCodeField.setText(kod);
            newCityField.setText(miasto);
            newCompanyField.setText(firma);
            newNIPField.setText(nip);
            newRegonField.setText(regon);
            
            editUserBtn.setVisible(true);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        ResultSet rs;
        PreparedStatement pst;
        Statement stmt;
        
        NewID noweID = new NewID();
        int userID = noweID.UstawNumer("kli_id","klient");
        String idU = Integer.toString(userID);
        idLabel.setText(idU);
        
        int placeID = noweID.UstawNumer("adr_id","adres");
        int companyID = noweID.UstawNumer("fir_id", "firma");
        
        String imie = newNameField.getText();
        String nazwisko = newSurnameField.getText();
        String haslo = hasloField.getText();
        String ulica = newAddressField.getText();
        String kodPoczt = newCodeField.getText();
        String miasto = newCityField.getText();
        String email = newMailField.getText();
        String nrtel = newPhoneField.getText();
        
        String firma = newCompanyField.getText();
        String nip = newNIPField.getText();
        String regon = newRegonField.getText();
        
        String addClient = "insert into Klient (kli_id, kli_imie, kli_nazwisko, kli_adres_id, kli_mail, kli_telefon, kli_haslo) values"
                + "('" + userID + "','" + imie + "','" + nazwisko + "','" + placeID + "','" + email +"','"
                + nrtel + "',')" + haslo + "')";
        
        String addPlace = "insert into Adres (adr_id, adr_ulica, adr_kod, adr_miasto, adr_klient_id) values"
                + "('" + placeID + "','" + ulica + "','" + kodPoczt + "','" + miasto + "','" + userID + "')";
        
        String addCompany = "insert into Firma (fir_id, fir_nazwa, fir_nip, fir_regon, fir_klient_id) values"
                + "('" + companyID + "','" + firma + "','" + nip + "','" + regon + "','" + userID + "')";
        
        
        
        try {
            conn = DataBase.Connection();
            stmt = conn.createStatement();
            
            if(imie.equals("") || nazwisko.equals("") || email.equals("") || haslo.equals("")) {
                JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie wymagane dane!");
                
            } else {
            
                if(firma.equals("") && nip.equals("") && regon.equals("")){
                    stmt.executeUpdate(addClient);
                    stmt.executeUpdate(addPlace);
                    JOptionPane.showMessageDialog(null, "Dodano nowego klienta!");
                
                } else if (!firma.equals("") && (nip.equals("") || regon.equals(""))) {
                    JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie dane dotyczące firmy!");
                
                } else if ((firma.equals("") || nip.equals("")) && !regon.equals("")) {
                    JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie dane dotyczące firmy!");
                
                } else if ((firma.equals("") || regon.equals("")) && !nip.equals("")) {
                    JOptionPane.showMessageDialog(null, "Uzupełnij wszystkie dane dotyczące firmy!");
                
                } else {
                    stmt.executeUpdate(addClient);
                    stmt.executeUpdate(addPlace);
                    stmt.executeUpdate(addCompany);
                    JOptionPane.showMessageDialog(null, "Dodano nowego klienta!");
                }
                
                newNameField.setText("");
                newSurnameField.setText("");
                hasloField.setText("");
                
                newAddressField.setText("");
                newCodeField.setText("");
                newCityField.setText("");
                newMailField.setText("");
                newPhoneField.setText("");
        
                newCompanyField.setText("");
                newNIPField.setText("");
                newRegonField.setText("");
                
                stmt.close();
                conn.close();
            }
            
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nie udało się dodać rekordu do bazy" + ex);
        }
    }//GEN-LAST:event_newUserBtnActionPerformed

    private void companyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyItemActionPerformed
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "companyPanel");
        
        FillTable uzupelnij = new FillTable();
        ResultSet rs2;
        PreparedStatement pst2;
        Statement stmt;

        uzupelnij.ClearTable(CompanyTable);
        
        String wybierzFirmy = "select fir_id, fir_nazwa, fir_nip, fir_regon, fir_klient_id, kli_imie, kli_nazwisko from "
                + "Firma, klient where fir_klient_id=kli_id";
            
        try {
            Connection conn = DataBase.Connection();

            pst2 = conn.prepareStatement(wybierzFirmy);
            rs2 = pst2.executeQuery();
            
            uzupelnij.FillCompany(CompanyTable, rs2);
            pst2.close(); rs2.close();
            
            conn.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w AdminPanel: " + ex);
        }
        
    }//GEN-LAST:event_companyItemActionPerformed

    private void newKlientItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newKlientItemActionPerformed
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "newClientPanel");

        editUserBtn.setVisible(false);
        newUserBtn.setVisible(true);
        hasloLabel.setVisible(true);
        hasloField.setVisible(true);
        
        newNameField.setText("");
        newSurnameField.setText("");
        newMailField.setText("");
        newPhoneField.setText("");
        newAddressField.setText("");
        newCodeField.setText("");
        newCityField.setText("");
        newCompanyField.setText("");
        newNIPField.setText("");
        newRegonField.setText("");
        hasloField.setText("");
        
    }//GEN-LAST:event_newKlientItemActionPerformed

    private void editUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtnActionPerformed
        
        String idkli = idLabel.getText(),
                imie = null, nazwisko = null, ulica = null, kodPoczt = null, miasto = null, 
                email = null, nrtel = null, firma = null, nip = null, regon = null;
        
        if(!(newNameField.getText()).equals(""))
            imie = newNameField.getText();
        if(!(newSurnameField.getText()).equals(""))
            nazwisko = newSurnameField.getText();
        if(!(newAddressField.getText()).equals(""))
            ulica = newAddressField.getText();
        if(!(newCodeField.getText()).equals(""))
            kodPoczt = newCodeField.getText();
        if(!(newCityField.getText()).equals(""))
            miasto = newCityField.getText();
        if(!(newMailField.getText()).equals(""))
            email = newMailField.getText();
        if(!(newPhoneField.getText()).equals(""))
            nrtel = newPhoneField.getText();
        
        if(!(newCompanyField.getText()).equals(""))
            firma = newCompanyField.getText();
        if(!(newNIPField.getText()).equals(""))
            nip = newNIPField.getText();
        if(!(newRegonField.getText()).equals(""))
            regon = newRegonField.getText();
        
        Statement stmt;
        ResultSet rs2; PreparedStatement pst2;
        ResultSet rs3; PreparedStatement pst3;
        
        String updateClient = "update Klient set kli_imie='" + imie +"', kli_nazwisko='" + nazwisko + "', kli_mail='"
                + email + "', kli_telefon='" + nrtel + "' where kli_id=" + idkli;
        
        String findAddress = "select * from Adres where adr_klient_id=" + idkli;
        
        String findCompany = "select * from Firma where fir_klient_id=" + idkli;
        
        String updateAddress = "update Adres set adr_ulica='" + ulica + "', adr_kod='" + kodPoczt +
                "', adr_miasto='" + miasto +"' where adr_klient_id=" + idkli;
        
        NewID noweid = new NewID();
        int adrID = noweid.UstawNumer("adr_id", "adres");
        int compID = noweid.UstawNumer("fir_id", "firma");
        
        String newAddress = "insert into Adres (adr_id, adr_ulica, adr_kod, adr_miasto, adr_klient_id) values "
                + "('" + adrID + "','" + ulica + "','" + kodPoczt + "','" + miasto + "','" + idkli + "')";
        
        String updateCompany = "update Firma set fir_nip='"+ nip + "', fir_regon='" + regon + "', fir_nazwa='" + firma +
                "' where fir_klient_id=" + idkli;
        
        String newCompany = "insert into Firma (fir_id, fir_nip, fir_regon, fir_nazwa, fir_klient_id) values ('"
                + compID +"','" + nip + "','" + regon + "','" + firma + "','" + idkli + "')"; 

        try {
            Connection conn = DataBase.Connection();

            stmt = conn.createStatement();
            pst = conn.prepareStatement(findAddress);
            rs = pst.executeQuery();
            
            stmt.executeUpdate(updateClient);

                if(rs.next()){
                    stmt.executeUpdate(updateAddress);
                    rs.close();
                    //JOptionPane.showMessageDialog(null, "Zaktualizowano adres");
                } else {
                    if(!(newAddressField.getText().equals("")) || !(newCodeField.getText().equals("")) || 
                            !(newCityField.getText().equals(""))) {
                    stmt.executeUpdate(newAddress);
                    rs.close();
                    JOptionPane.showMessageDialog(null, "Dodano nowy adres do klienta");
                }
            }
            pst.close();
            
            pst2 = conn.prepareStatement(findCompany);
            rs2 = pst2.executeQuery();

                if(rs2.next()) {
                    stmt.executeUpdate(updateCompany);
                    rs2.close();
                    //JOptionPane.showMessageDialog(null, "Zaktualizowano dane firmy");
                } else {
                    if(!(newCompanyField.getText().equals("")) || !(newNIPField.getText().equals("")) 
                            || !(newRegonField.getText().equals(""))) {
                    stmt.executeUpdate(newCompany);
                    rs2.close();
                    JOptionPane.showMessageDialog(null, "Dodano nową firmę do klienta");
                }
            }
            pst2.close();

            stmt.close();
            conn.close();
            
            JOptionPane.showMessageDialog(null, "Zaktualizowano dane");
                    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nie udało się zaktualizować rekordu! " + ex);
        } 
    }//GEN-LAST:event_editUserBtnActionPerformed

    private void editCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCompanyBtnActionPerformed
        
        int index = CompanyTable.getSelectedRow();
        System.out.println("Wybrany index" + index);
        
        String idFir = (String) CompanyTable.getValueAt(index, 0);
        String nazwaFir = (String) CompanyTable.getValueAt(index, 1);
        String nipFir = (String) CompanyTable.getValueAt(index, 2);
        String regonFir = (String) CompanyTable.getValueAt(index, 3);
        String idKli = (String) CompanyTable.getValueAt(index, 5);
        
        String imie = "", nazwisko = "", email = "", telefon = "", ulica = "", miasto = "", kod = ""; 
        
        String selectWla = "select * from klient, adres, firma where kli_id=" + idKli + " and kli_id=adr_klient_id "
                + "and kli_id=fir_klient_id";
        
        try {
            Connection conn = DataBase.Connection();
            
            pst = conn.prepareStatement(selectWla);
            rs = pst.executeQuery();
            
            if(rs.next()) {
                imie = rs.getString("kli_imie");
                nazwisko = rs.getString("kli_nazwisko");
                email = rs.getString("kli_mail");
                telefon = rs.getString("kli_telefon");
                ulica = rs.getString("adr_ulica");
                kod = rs.getString("adr_kod");
                miasto = rs.getString("adr_miasto");
            }
            
            pst.close(); rs.close(); conn.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w wyszukaniu firmy dla podanego klienta " + ex);
        }
        
        if(evt.getSource()== editCompanyBtn) {
            CardLayout card = (CardLayout) changingPanel2.getLayout();
            card.show(changingPanel2, "newClientPanel");
            
            newUserBtn.setVisible(false);
            
            idCompLabel.setText(idFir);
            idLabel.setText(idKli);
            newNameField.setText(imie);
            newSurnameField.setText(nazwisko);
            newMailField.setText(email);
            newPhoneField.setText(telefon);
            newAddressField.setText(ulica);
            newCodeField.setText(kod);
            newCityField.setText(miasto);
            newCompanyField.setText(nazwaFir);
            newNIPField.setText(nipFir);
            newRegonField.setText(regonFir);
            
            editUserBtn.setVisible(true);
            idCompLabel.setVisible(false);
            jLabel12.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_editCompanyBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        Statement stmt;
        FillTable uzupelnij = new FillTable();
        PreparedStatement pst2; ResultSet rs2;
        
        int index = clientsTable.getSelectedRow();
        String nr_id = (String) clientsTable.getValueAt(index, 0);
        
        String usunKlienta = "delete from klient where kli_id=" + nr_id;
        String usunFirme = "delete from firma where fir_klient_id=" + nr_id;
        String usunAdres = "delete from Adres where adr_klient_id=" + nr_id;
        
        String wybierzKlientow = "select kli_id, kli_imie, kli_nazwisko, kli_mail, kli_telefon, adr_ulica, adr_kod, "
                + "adr_miasto from klient, adres where kli_id=adr_klient_id and adr_id=kli_adres_id";
        
        String wybierzFirmy = "select fir_id, fir_nazwa, fir_nip, fir_regon, fir_klient_id, kli_imie, kli_nazwisko from "
                + "Firma, klient  where fir_klient_id=kli_id";
        
        try {
            Connection conn = DataBase.Connection();
            stmt = conn.createStatement();
            pst = conn.prepareStatement(wybierzKlientow);
            rs = pst.executeQuery();
            
            stmt.executeUpdate(usunKlienta);
            stmt.executeUpdate(usunFirme);
            stmt.executeUpdate(usunAdres);
            
            pst2 = conn.prepareStatement(wybierzFirmy);
            rs2 = pst2.executeQuery();
            
            uzupelnij.ClearTable(clientsTable);
            uzupelnij.FillClients(clientsTable, rs);
            uzupelnij.ClearTable(CompanyTable);
            uzupelnij.FillCompany(CompanyTable,rs2);
            
            stmt.close(); pst2.close(); rs2.close();
            pst.close(); rs.close();
            conn.close();
            
            JOptionPane.showMessageDialog(null, "Usunięto dane z bazy");
            
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nie udało się usunąć danych: " + ex);
        }                
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void logoffItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffItemActionPerformed
        dispose();
        
        UserPanel newPanel = new UserPanel();
        newPanel.setVisible(true);
    }//GEN-LAST:event_logoffItemActionPerformed

    private void deleteCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompanyBtnActionPerformed
        
        Statement stmt;
        FillTable uzupelnij = new FillTable();

        int index = CompanyTable.getSelectedRow();
        String nr_id = (String) CompanyTable.getValueAt(index, 0);

        String usunFirme = "delete from firma where fir_id=" + nr_id;

        String wybierzFirmy = "select fir_id, fir_nazwa, fir_nip, fir_regon, fir_klient_id, kli_imie, kli_nazwisko from "
                + "Firma, klient  where fir_klient_id=kli_id";
        
        try {
            Connection conn = DataBase.Connection();
            stmt = conn.createStatement();
            pst = conn.prepareStatement(wybierzFirmy);
            rs = pst.executeQuery();

            stmt.executeUpdate(usunFirme);

            uzupelnij.ClearTable(CompanyTable);
            uzupelnij.FillCompany(CompanyTable,rs);
            
            stmt.close();
            pst.close(); rs.close();
            conn.close();
            
            JOptionPane.showMessageDialog(null, "Usunięto firmę z bazy");
            
        } catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nie udało się usunąć danych: " + ex);
        }       
        
        
    }//GEN-LAST:event_deleteCompanyBtnActionPerformed

    private void rulesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesItemActionPerformed
        
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "programPanel");
        
        String wybierzPunkty = "select * from program_lojal where pro_id=1";
        
        try {
            Connection conn = DataBase.Connection();
            
            pst = conn.prepareStatement(wybierzPunkty);
            rs = pst.executeQuery();
   
            tank95Field.setText(rs.getString("pro_e95"));
            tank98Field.setText(rs.getString("pro_e98"));
            tankONField.setText(rs.getString("pro_on"));
            tankLPGField.setText(rs.getString("pro_lpg"));
            mycieField.setText(rs.getString("pro_wash"));
            woskField.setText(rs.getString("pro_wax"));
                    
            benzPointsField.setText(rs.getString("pro_pkt_paliwo"));
            lpgPointsField.setText(rs.getString("pro_pkt_gaz"));
            washField.setText(rs.getString("pro_pkt_myjnia"));
            waxField.setText(rs.getString("pro_pkt_wosk"));
            
            rs.close(); pst.close(); conn.close();
        
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Błąd " + ex);
        }

       
    }//GEN-LAST:event_rulesItemActionPerformed

    private void tank95FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tank95FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tank95FieldActionPerformed

    private void changePointsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePointsBtnActionPerformed
        
        String e95 = tank95Field.getText();
        String e98 = tank98Field.getText();
        String on = tankONField.getText();
        String lpg = tankLPGField.getText();
        String mycie = mycieField.getText();
        String wosk = woskField.getText();

        Statement stmt;
        UserPanel panel = new UserPanel();
       
        String zmienPunkty = "update program_lojal set pro_e95=" + e95 + ", pro_e98=" + e98 +
                ", pro_on=" + on + ", pro_lpg=" + lpg + ", pro_wash=" + mycie + ", pro_wax=" + wosk;
        
        try {
            Connection conn = DataBase.Connection();
            stmt = conn.createStatement();
            stmt.executeUpdate(zmienPunkty);
            
            stmt.close(); conn.close();
            
            panel.UstawLabele();
            JOptionPane.showMessageDialog(null, "Zmieniono punkty");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd " + ex);
        }

    }//GEN-LAST:event_changePointsBtnActionPerformed

    private void changePoints2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePoints2BtnActionPerformed
        
        String benz = benzPointsField.getText();
        String lpg = lpgPointsField.getText();
        String wash = washField.getText();
        String wax = waxField.getText();
        
        Statement stmt;
        UserPanel panel = new UserPanel();
        
        String zmienPunkty = "update program_lojal set pro_pkt_paliwo=" + benz + ", pro_pkt_gaz=" + lpg +
                ", pro_pkt_myjnia=" + wash + ", pro_pkt_wosk=" + wax;
                
        try {
            Connection conn = DataBase.Connection();
            stmt = conn.createStatement();
            stmt.executeUpdate(zmienPunkty);
            
            stmt.close(); conn.close();
            
            panel.UstawLabele();
            JOptionPane.showMessageDialog(null, "Zmieniono punkty");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd " + ex);
        }
        
    }//GEN-LAST:event_changePoints2BtnActionPerformed

    private void changePriceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePriceMenuActionPerformed
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "priceCard");
        
        
        String ustalCeny = "select * from Parametry where Par_ID=1";

        try {
            Connection conn = DataBase.Connection();
            
            pst = conn.prepareStatement(ustalCeny);
            rs = pst.executeQuery();
           
            oil2TextField.setText(rs.getString("Par_e95"));
            oil1TextField.setText(rs.getString("Par_e98"));
            gasTextField.setText(rs.getString("Par_lpg"));
            ONTextField.setText(rs.getString("Par_ON"));
            washTextField.setText(rs.getString("Par_mycie"));
            wash2TextField.setText(rs.getString("Par_wosk"));          
            
            rs.close(); pst.close(); conn.close();
        
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(null, "Błąd " + ex);
        }
    }//GEN-LAST:event_changePriceMenuActionPerformed

    private void SaveChangesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveChangesBtnActionPerformed
        
        String benz95 = oil2TextField.getText();
        String benz98 = oil1TextField.getText();
        String lpg = gasTextField.getText();
        String on = ONTextField.getText();
        String wash = washTextField.getText();
        String wax = wash2TextField.getText();
        
        Statement stmt;
        //UserPanel cennik = new UserPanel();
       
        String zmienCene = "update Parametry set Par_e95='" + benz95 + "', Par_e98='" + benz98 + "', Par_ON='" 
                + on + "', Par_lpg='" + lpg + "', Par_mycie='" + wash + "', Par_wosk='" + wax + "'";
        
        try {
            Connection conn = DataBase.Connection();
            stmt = conn.createStatement();
            stmt.executeUpdate(zmienCene);
            
            stmt.close(); conn.close();
            
            //cennik.CenywWindow();
            JOptionPane.showMessageDialog(null, "Zaktualizowano ceny!");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w admin " + ex);
        }
        
    }//GEN-LAST:event_SaveChangesBtnActionPerformed

    private void cameraItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraItemActionPerformed
               
//        changingPanel2.removeAll();
//        changingPanel2.add(monitoringPanel);
//        changingPanel2.repaint();
//        changingPanel2.revalidate();
        
        CardLayout card = (CardLayout) changingPanel2.getLayout();
        card.show(changingPanel2, "cardMoni");
        
       
        
    }//GEN-LAST:event_cameraItemActionPerformed

    private void washItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

        FillTable uzupelnij = new FillTable();
        ResultSet rs2;
        PreparedStatement pst2;
        Statement stmt;
        
        uzupelnij.ClearTable(clientsTable);
        uzupelnij.ClearTable(CompanyTable);
        
        String wybierzKlientow = "select kli_id, kli_imie, kli_nazwisko, kli_mail, kli_telefon, adr_ulica, adr_kod, "
                + "adr_miasto from klient, adres where kli_id=adr_klient_id and adr_id=kli_adres_id";
        
        String wybierzFirmy = "select fir_id, fir_nazwa, fir_nip, fir_regon, fir_klient_id, kli_imie, kli_nazwisko from "
                + "Firma, klient where fir_klient_id=kli_id";
            
        try {
            Connection conn = DataBase.Connection();
            pst = conn.prepareStatement(wybierzKlientow);
            rs = pst.executeQuery();
            
            uzupelnij.FillClients(clientsTable, rs);
            pst.close(); rs.close();
            
            pst2 = conn.prepareStatement(wybierzFirmy);
            rs2 = pst2.executeQuery();
            
            uzupelnij.FillCompany(CompanyTable, rs2);
            pst2.close(); rs2.close();
            
            conn.close();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Błąd w AdminPanel: " + ex);
        }         
        
        clientsTable.setAutoCreateRowSorter(true);
        CompanyTable.setAutoCreateRowSorter(true);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CompanyTable;
    private javax.swing.JTextField ONTextField;
    private javax.swing.JPanel PricePanel;
    private javax.swing.JButton SaveChangesBtn;
    private javax.swing.JTextField benzPointsField;
    private javax.swing.JMenuItem cameraItem;
    private javax.swing.JMenu cameraMenu;
    private javax.swing.JButton changePoints2Btn;
    private javax.swing.JButton changePointsBtn;
    private javax.swing.JMenuItem changePriceMenu;
    private javax.swing.JPanel changingPanel2;
    private javax.swing.JTable clientsTable;
    private javax.swing.JMenuItem companyItem;
    private javax.swing.JPanel companyPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteCompanyBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editCompanyBtn;
    private javax.swing.JButton editUserBtn;
    private javax.swing.JTextField gasTextField;
    private javax.swing.JPasswordField hasloField;
    private javax.swing.JLabel hasloLabel;
    private javax.swing.JLabel idCompLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel klienciCard;
    private javax.swing.JMenuItem klientsItem;
    private javax.swing.JMenuItem logoffItem;
    private javax.swing.JMenu loyProgMenu;
    private javax.swing.JTextField lpgPointsField;
    private javax.swing.JTextField mycieField;
    private javax.swing.JTextField newAddressField;
    private javax.swing.JTextField newCityField;
    private javax.swing.JPanel newClientPanel;
    private javax.swing.JTextField newCodeField;
    private javax.swing.JTextField newCompanyField;
    private javax.swing.JMenuItem newKlientItem;
    private javax.swing.JTextField newMailField;
    private javax.swing.JMenu newMenu;
    private javax.swing.JTextField newNIPField;
    private javax.swing.JTextField newNameField;
    private javax.swing.JTextField newPhoneField;
    private javax.swing.JTextField newRegonField;
    private javax.swing.JTextField newSurnameField;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JTextField oil1TextField;
    private javax.swing.JTextField oil2TextField;
    private javax.swing.JMenu priceMenu;
    private javax.swing.JPanel programPanel;
    private javax.swing.JMenuItem rulesItem;
    private javax.swing.JTextField tank95Field;
    private javax.swing.JTextField tank98Field;
    private javax.swing.JTextField tankLPGField;
    private javax.swing.JTextField tankONField;
    private javax.swing.JLabel tankowanieelpegie;
    private javax.swing.JTextField wash2TextField;
    private javax.swing.JTextField washField;
    private javax.swing.JMenuItem washItem;
    private javax.swing.JMenu washMenu;
    private javax.swing.JTextField washTextField;
    private javax.swing.JTextField waxField;
    private javax.swing.JTextField woskField;
    // End of variables declaration//GEN-END:variables
}
