/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stacja;

/**
 *
 * @author Katarzyna
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        newMenu = new javax.swing.JMenu();
        klientsItem = new javax.swing.JMenuItem();
        newKlientItem = new javax.swing.JMenuItem();
        loyProgMenu = new javax.swing.JMenu();
        rulesItem = new javax.swing.JMenuItem();
        listItem = new javax.swing.JMenuItem();
        washMenu = new javax.swing.JMenu();
        washItem = new javax.swing.JMenuItem();
        cameraMenu = new javax.swing.JMenu();
        cameraItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newMenu.setText("Klienci");
        newMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMenuMouseClicked(evt);
            }
        });
        newMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuActionPerformed(evt);
            }
        });

        klientsItem.setText("Zarejestrowani klienci");
        klientsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientsItemActionPerformed(evt);
            }
        });
        newMenu.add(klientsItem);

        newKlientItem.setText("Dodaj klienta");
        newMenu.add(newKlientItem);

        jMenuBar1.add(newMenu);

        loyProgMenu.setText("Program lojalnościowy");

        rulesItem.setText("Zasady programu");
        loyProgMenu.add(rulesItem);

        listItem.setText("Lista uczestników programu");
        loyProgMenu.add(listItem);

        jMenuBar1.add(loyProgMenu);

        washMenu.setText("Myjnia");

        washItem.setText("Kalendarz");
        washMenu.add(washItem);

        jMenuBar1.add(washMenu);

        cameraMenu.setText("Monitoring");

        cameraItem.setText("Kamery");
        cameraMenu.add(cameraItem);

        jMenuBar1.add(cameraMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void klientsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klientsItemActionPerformed
        
    }//GEN-LAST:event_klientsItemActionPerformed

    private void newMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMenuMouseClicked
        
    }//GEN-LAST:event_newMenuMouseClicked

    private void newMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuActionPerformed

    }//GEN-LAST:event_newMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cameraItem;
    private javax.swing.JMenu cameraMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem klientsItem;
    private javax.swing.JMenuItem listItem;
    private javax.swing.JMenu loyProgMenu;
    private javax.swing.JMenuItem newKlientItem;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem rulesItem;
    private javax.swing.JMenuItem washItem;
    private javax.swing.JMenu washMenu;
    // End of variables declaration//GEN-END:variables
}
